from .configuration_bert import BertConfig as AlbertConfig
from .modeling_albert import AlbertForTokenClassification,AlbertForSequenceClassification
from .tokenization_bert import BertTokenizer as AlbertTokenizer